README.md
docs/terraform.md
main.tf
variables.tf

This allows a user of this module to specify additional arbitrary policies they would like to apply to the bucket.
Currently, the `allow_encrypted_uploads_only` option uses the only attachment available for bucket policies on the s3 bucket.  If a user needs to add their own policies, say to enable cross account access to the bucket, they cannot.  This allows them to do that.
```
data "aws_iam_policy_document" "additional_policies" {
count = "${length(var.trusted_roles) > 0 ? 1 : 0}"
statement {
effect = "Allow"
principals = {
type = "AWS"
identifiers = "${var.trusted_roles}"
}
actions = [
"s3:Get*",
"s3:Put*",
"s3:List*"
]
resources = [
"${module.s3_bucket.bucket_arn}"
]
}
}
module "s3_bucket" {
source                       = "git::https://github.com/asiegman/terraform-aws-s3-bucket.git?re …
```

Adds concept of additional bucket policies

---

README.md
docs/terraform.md
main.tf
variables.tf

This is a copy from : https://github.com/cloudposse/terraform-aws-s3-log-storage/blob/master/main.tf
to enable additional options for the s3 lifecycle expirations
adding support for abort_incomplete_multipart_upload_days

adding dynamics to allow for other expiration types

---

README.md
docs/terraform.md
main.tf
variables.tf

Originally from https://github.com/terraform-aws-modules/terraform-aws-s3-bucket

Add the ability to specify cors-rules

---

.github/workflows/chatops.yml
.github/workflows/test.yml

* use proper comment id
* the previous syntax was meant for cross-repo dispatch events

fix reaction

---

README.md
README.yaml
docs/terraform.md
main.tf
variables.tf

This will change the default behavior to now block public access to the bucket.  All options can be configured.  
This mirrors a recent update to the https://github.com/cloudposse/terraform-aws-s3-log-storage module.
This also supersedes https://github.com/cloudposse/terraform-aws-s3-bucket/pull/23

Optionally allow public access to the bucket, default is now to block

---

README.md
docs/terraform.md
main.tf

This change will allow us to seamlessly support other AWS partitions
such as aws-us-gov.
* Support other AWS partitions (such as aws-us-gov).
* This change is a NOOP for existing resources.
* The module hardcodes the partition component of the ARN, making it impossible to use this module in other partitions.
* See Amazon ARN [syntax](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arns-syntax)

Remove hardcoded ARN partition information

---

README.md
docs/terraform.md
versions.tf

do not restrict the aws provider version to just v2
https://github.com/cloudposse/terraform-aws-route53-cluster-hostname/issues/23
the aws cloud provider has v13 fixes and requirements also
`closes #46`
https://github.com/cloudposse/terraform-aws-s3-bucket/issues/46

update AWS provider pinning to v3 for TF 0.13 version compat

---

README.md
docs/terraform.md
examples/complete/main.tf
examples/complete/outputs.tf
main.tf
outputs.tf
versions.tf

set minimum versions for providers without pinning to a specific major version
the current method makes it very difficult to maintain or upgrade consistent provider versions within a project
closes #46 
https://www.terraform.io/docs/configuration/provider-requirements.html#best-practices-for-provider-versions
https://github.com/cloudposse/terraform-aws-iam-system-user/pull/33
https://github.com/cloudposse/terraform-aws-iam-s3-user/pull/19

use minimum versions for provider pinning

---

README.md
docs/terraform.md
versions.tf

I was using some of your other aws terraform projects and because they want version `~> 2.0` mostly. And this one wants >3.0 then it would not work:
```
Error: provider.aws: no suitable version installed
version requirements: ">= 2.0,>= 2.0,>= 2.0,>= 2.0,>= 3.0,>= 3.0,~> 2.0,~> 2.0,~> 2.0,~> 2.0,~> 2.0,~> 2.0,~> 2.0"
versions installed: "2.70.0"
```
So I've relaxed the requirement in this repo to resolve this.

Fix version clash with other cloudposse repos

---

README.md
context.tf
docs/targets.md
docs/terraform.md
examples/complete/context.tf
versions.tf

- update context.tf to v0.23.0 
- minimum required Terraform version bumped to 0.13.0 
- readme updated, Bridgecrew compliance badges added
- It allows for setting the letter case of tag names and labels
- we have dropped support for Terraform 0.12
- To be able see and fix the recommendations from Bridgecrew so we can position our modules as standards compliant

minimum required Terraform version bumped to 0.13.0, context.tf updated, readme updated

---

replication.tf

* Add missing replication policy permissions
* Without this permission cross-account replication is not possible
* https://github.com/cloudposse/terraform-aws-s3-bucket/issues/68
* `closes #68`

Cross-account replication fix

---

README.md
docs/terraform.md
main.tf
variables.tf

Support transition to the deep archive storage class
We need this for our business.

S3deeparchive support

---

README.md
main.tf

* Fixing a bug where the bucket policy would flip-flop on Terraform apply if `var.policy` and any of `var.allow_ssl_requests_only`, `var.allow_encrypted_uploads_only` were set
* The `aws_s3_bucket.policy` attribute was competing with the `aws_s3_bucket_policy` resource

Removing policy attribute for S3 bucket

---

README.md
docs/terraform.md
outputs.tf

* Add output for replication IAM Role ARN
* An output for the delegated replication IAM Role does not exist
N/A

Feat: Add Output for Replication IAM Role ARN

---

.github/auto-release.yml
.github/workflows/auto-release.yml
README.md
docs/terraform.md
main.tf
variables.tf

* We already use this module for S3 and want to be able to use it to deploy S3 buckets with static website hosting configs
* The change in this PR adds that support
* Would like to be able to use [cloudposse/terraform-aws-s3-bucket](https://github.com/cloudposse/terraform-aws-s3-bucket) (this module) to deploy buckets that support static website hosting and have very custom-tailored S3 bucket policy.
* Tried using [cloudposse/terraform-aws-s3-website](https://github.com/cloudposse/terraform-aws-s3-website) for the same need and hit the roadblock of it not supporting custom bucket policies.
* Our TF modules (in our org) are pinned down to use `cloudposse/terraform-aws-s3-bucket` for most S3 bucket needs, so we didn't have interest in using and modifying …

Ability to specify website hosting configuration

---

main.tf

* The `privileged_principal_arns` option is not creating a bucket policy.
* A check at the `s3_bucket_policy is missing` 
* https://github.com/cloudposse/terraform-aws-s3-bucket/issues/100

fix privileged_principal_arns not creating bucket policy

---

main.tf

Enabling `versioning` on a bucket is a permanent action that cannot be disabled. For this reason, when `versioning` attribute is added to the s3 resource, the bucket is prepared to be `versioned` and put in suspended mode. The only way to avoid this and keep the versioning disabled is to not add the `versioning` attribute at all.
We were discussing this in [this bug](https://github.com/cloudposse/terraform-aws-s3-bucket/issues/76) and @aknysh posted a snipped which is removing the attribute, making it possible to set `versioning` off instead of enabled but suspended.
I'm just adding that snippet, [there's another PR](https://github.com/cloudposse/terraform-aws-s3-bucket/pull/77) which is apparently changing more than just the versioning and it seems abandoned (opened in February 2021, had …

Dynamic block for versioning added

---

main.tf
variables.tf

* There are no control ability for enable `Delete marker replication` in this module
* The reason of this was because empty `filter` would always be generated in this [line](https://github.com/cloudposse/terraform-aws-s3-bucket/blob/816e61ab796a159e9f949350a1645576761dad8a/main.tf#L208)
* And this will disable the `Delete marker replication` option in replication rule
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#delete_marker_replication_status

feat: add delete_marker_replication_status in replication rules

---

README.md
docs/terraform.md
examples/complete/main.tf
examples/complete/outputs.tf
examples/complete/replication.tf
examples/complete/replication.us-east-2.tfvars
examples/complete/variables.tf
main.tf
variables.tf
versions.tf

* Enable replication metrics by default
* Allow override via variables
AWS provider requirements update due to: https://github.com/hashicorp/terraform-provider-aws/pull/21901
* To be able to track replication status
https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-metrics.html

Feat: Enable Replication Metrics

---

README.md
docs/terraform.md
versions.tf

- Update version pinning now that [AWS provider v4.9.0] restores compatibility
- Give people a longer period of time to adapt to changes
This will become version 1.0

Update version pinning for AWS provider

---

main.tf
test/src/go.mod
test/src/go.sum

* Use object lock enabled
* Deprecation of dynamic `object_lock_configuration` for `object_lock_enabled`
```hcl
│ Warning: Argument is deprecated
│
│   with module.bucket.aws_s3_bucket.default,
│   on .terraform/modules/bucket/main.tf line 30, in resource "aws_s3_bucket" "default":
│   30: resource "aws_s3_bucket" "default" {
│
│ Use the top-level parameter object_lock_enabled and the aws_s3_bucket_object_lock_configuration resource instead
```
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#object_lock_enabled
* Previous PR https://github.com/cloudposse/terraform-aws-s3-bucket/pull/144 (this did not use `object_lock_enabled` and only removed the dynamic)

Use object lock enabled

---

replication.tf
variables.tf

* Adds support for assigning [permission boundaries](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html) to the replication IAM role
* Our AWS environment enforces permission boundaries on all IAM roles to follow AWS best practices with security.
* [AWS IAM Access Policies](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html)

Add support for permission boundaries on replication IAM role

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/mergify.yml
.github/renovate.json
.github/workflows/auto-context.yml
.github/workflows/auto-format.yml
.github/workflows/auto-readme.yml
.github/workflows/auto-release.yml
.github/workflows/chatops.yml
.github/workflows/validate-codeowners.yml
README.md
main.tf

* Always create an `aws_s3_bucket_versioning` resource to track changes made to bucket versioning configuration
* When there is no `aws_s3_bucket_versioning`, the expectation is that the bucket versioning is disabled/suspend for the bucket. If bucket versioning is turned on outside of terraform (e.g. through the console), the change is not detected by terraform unless the `aws_s3_bucket_versioning` resource exists.
* Closes #171

Always include `aws_s3_bucket_versioning` resource

---

examples/complete/main.tf
examples/complete/outputs.tf
examples/complete/privileged-principals.tf
lifecycle.tf
main.tf
outputs.tf
test/src/Makefile

Linter fixes
Bump test timeout
Verifying tests with AWS provider V5
Maintenance 
https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0

Fix linters / Retest on AWS provider V5

---

main.tf

- removes `local.public_access_block_enabled`
- includes `aws_s3_bucket_public_access_block` for every bucket
- `aws_s3_bucket_public_access_block` was not getting set, which prevented the use of public buckets.
- https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-s3-security-best-practices-buckets-default/

Fix Public Bucket Creation

---

README.md
main.tf

- Changed `var.source_policy_documents` to `local.source_policy_documents` so `var.policy` usage was still supported
- The ternary check uses `var,source_policy_documents` so `var.policy` being combined with `var.source_policy_documents` into `local.source_policy_documents` does not provide `true` for the ternary to execute
- https://github.com/cloudposse/terraform-aws-config-storage/pull/39

Fix `source_policy_documents` combined with `var.policy` being ignored

---

README.md
main.tf

* When trying to create an S3 bucket, the following error is encountered:
```
Error: Invalid dynamic for_each value
on .terraform/main.tf line 225, in resource "aws_s3_bucket_replication_configuration" "default":
225:           for_each = try(compact(concat(
226:             [try(rule.value.destination.encryption_configuration.replica_kms_key_id, "")],
227:             [try(rule.value.destination.replica_kms_key_id, "")]
228:           ))[0], [])
├────────────────
│ rule.value.destination.encryption_configuration is null
│ rule.value.destination.replica_kms_key_id is "arn:aws:kms:my-region:my-account-id:my-key-alias"
Cannot use a string value in for_each. An iterable collection is required.
```
* This is caused in my case by having …

Fix bug in setting dynamic `encryption_configuration` value

---

main.tf

Replaced the count with a for_each inside `aws_s3_bucket_logging.default`
there's no point in the try since the type is clearly defined as list
When the `bucket_name` within `logging` attribute is dynamically defined, like in the case of referencing a bucket created by terraform for logging
```hcl
logging = [
{
bucket_name = module.logging_bucket.bucket_id
prefix      = "data/"
}
]
```
we get this error 
For each can work better in this case and will solve the previous error

fix: use for_each instead of count in aws_s3_bucket_logging

---

replication.tf

- use new destination.bucket key in policy
- Support both deprecated `destination_bucket` and new `destination.bucket`
- Previous changes created `destination.bucket` and left `destination_bucket` for backwards compatibility, as stated in variables.tf, and forgot to include the new value in the IAM policy
- Closes #215

fix: use new destination.bucket key in policy
